languageCode = "de-DE"
title = "Andreas Kleiber"
theme = "hugo-theme-cleanwhite"

[params]
  url = "https://andreaskleiber.de/"
  header_image = "images/crownbracketdawn.jpg"
  title = "Andreas Kleiber - Personal Blog"
  slogan = "Do it!"
  SEOTitle = "Personal Blog"
  keyword = "Andreas, Kleiber, AWS, cooking, software engineering, cloud computing, serverless"

  # Sidebar settings
  sidebar_about_description = "Me"
  sidebar_avatar = "images/anon-andi.jpg"
  about_me = true

  featured_tags = true
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404.jpg"
  title_404 = "What you where looking for is not here. I am sorry! Please accept my apology. Here is a cat for you. ฅ^•ﻌ•^ฅ"

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  linkedin       = "https://www.linkedin.com/in/andreas-kleiber-025576b7"
  github         = "https://github.com/akleiber"